/* ACCOUNT */
export const ACCOUNT_RETRIEVED = "ACCOUNT_RETRIEVED";
export const ACCOUNT_UPDATED = "ACCOUNT_UPDATED";

/* BOOKMARKS */
export const BOOKMARK_CREATED = "BOOKMARK_CREATED";
export const BOOKMARK_EDITED = "BOOKMARK_EDITED";
export const BOOKMARK_VIEWED = "BOOKMARK_VIEWED";
export const BOOKMARK_DELETED = "BOOKMARK_DELETED";
export const BOOKMARKS_RETRIEVED = "BOOKMARKS_RETRIEVED";
export const BOOKMARKS_FILTERED = "BOOKMARKS_FILTERED";
export const BOOKMARKS_SORTED = "BOOKMARKS_SORTED";
export const BOOKMARK_SELECTED = "BOOKMARK_SELECTED";
export const BOOKMARKS_UNSELECTED = "BOOKMARKS_UNSELECTED";
export const TAGS_UPDATED = "TAGS_UPDATED";

/* MENUS */
export const EXTERNAL_CLICK = "EXTERNAL_CLICK";
export const MENU_CLOSED = "MENU_CLOSED";
export const MENU_OPENED = "MENU_OPENED";

/* MODALS */
export const MODAL_CLOSED = "MODAL_CLOSED";
export const MODAL_OPENED = "MODAL_OPENED";

/* INPUTS */
export const INPUT_CREATED = "INPUT_CREATED";
export const INPUT_UPDATED = "INPUT_UPDATED";
export const INPUT_DELETED = "INPUT_DELETED";
export const IMAGE_INPUT_CREATED = "IMAGE_INPUT_CREATED";
export const IMAGE_INPUT_UPDATED = "IMAGE_INPUT_UPDATED";
export const MULTI_SELECTS_UNSELECTED = "MULTI_SELECTS_UNSELECTED";
export const TAG_INPUT_CREATED = "TAG_INPUT_CREATED";
export const TAG_INPUT_UPDATED = "TAG_INPUT_UPDATED";
export const TAG_ADDED = "TAG_ADDED";
export const TAG_REMOVED = "TAG_REMOVED";

/* PANELS */
export const PANEL_CREATED = "PANEL_CREATED";
export const PANEL_UPDATED = "PANEL_UPDATED";
export const PANEL_DELETED = "PANEL_DELETED";